### ISSUE TITLE
Fix the Query issue

### ISSUE THREAD

**Issue by vchrombie** [vchrombie/hackbunch#13]
As per the new GitHub API Release (https://developer.github.com/v4/changelog/2019-10-09-schema-changes), our script seems to be broken as of now. Find a new approach to solve this.

**Comment by adiaux** [comment]
I'll take up this issue, it sounds interesting.

**Comment by vchrombie** [comment]
> I'll take up this issue, it sounds interesting.

@adiaux, are you sure?

**Comment by adiaux** [comment]
Yeah @vchrombie :smile:

**Comment by vchrombie** [comment]
Awesome, assigned to you. Waiting for your PR. :slightly_smiling_face:
