### ISSUE TITLE
Make the front-end for the Flask app

### ISSUE THREAD

**Issue by vchrombie** [vchrombie/hackbunch#3]
The front-end should a text box for the input of the username, a button for running the script. Make the front-end for displaying the results, once the #2 is done.

**Comment by vchrombie** [comment]
The UI can be simple. You can use Bootstrap. Please let me know if you have any more things to be clarified.

**Comment by satanb4** [comment]
Has this issue been addressed? If not, then please list the requirements and I'll setup the front-end.
